# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Hosted Windows 2019 with VS2019
  demands: githubreps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'Pay-As-You-Go'
    ScriptPath: 'AzureResourceGroupDemo/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'vbk' -ResourceGroupLocation 'Southeast Asia'
    azurePowerShellVersion: LatestVersion
